import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AuthProvider } from "@/contexts/authContext";

export const metadata = {
  title: "apex",
  description: "Generated by apex",
};

export default function layout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AntdRegistry>
          <AuthProvider>{children}</AuthProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
