import "../styles/globals.css"
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/contexts/authContext";

export const metadata = {
  title: "apex",
  description: "Generated by apex",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <AntdRegistry>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
